# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_androiddevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androiddevice',
            name='device_id',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
