# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20170705_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpost',
            options={'ordering': ('image_url',)},
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='user',
        ),
        migrations.AddField(
            model_name='userpost',
            name='show_info',
            field=models.BooleanField(default=False),
        ),
    ]
